# Generated by Django 3.0.6 on 2020-05-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetScrapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=25)),
                ('currency_name', models.CharField(max_length=50)),
                ('buying_rate', models.CharField(max_length=20)),
                ('selling_rate', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Exchange_Rates',
                'ordering': ['currency_name'],
            },
        ),
    ]
