# Generated by Django 3.0.6 on 2020-05-22 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeRate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getscrapy',
            name='updated',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 22, 11, 24, 55, 683621)),
        ),
    ]
