# Generated by Django 3.0.6 on 2020-05-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeRate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getscrapy',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
