# Generated by Django 3.0.6 on 2020-05-22 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeRate', '0002_auto_20200522_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getscrapy',
            name='updated',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
